name: Create Cypress report
on:
  push:
    branches:
      - "master"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Level-1 DHIS2 client application
        run: |
          echo 'Started level-1 analysis'
          echo "level1Status='{"label": "DHIS2-level1", "status": "pass"}'" >> $GITHUB_ENV
          echo $(npm run badge-status)
