name: Create Cypress report
on:
  push:
    branches:
      - 'master'

jobs:
  
 e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'
      
      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true
      
      - name: Merge test results into one
        run: npm run report:merge
      
      - name: Generate HTML report
        run: npm run report:generate
      
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
